/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservationsystem;

/**
 *
 * @author Jimmy
 */
public class AdminControl extends javax.swing.JFrame {

    /**
     * Creates new form AdminControl
     */
    public AdminControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        manageBus = new javax.swing.JMenu();
        addBus = new javax.swing.JMenuItem();
        editBus = new javax.swing.JMenuItem();
        deleteBus = new javax.swing.JMenuItem();
        allBus = new javax.swing.JMenuItem();
        busTime = new javax.swing.JMenu();
        addBusTime = new javax.swing.JMenuItem();
        editBusTime = new javax.swing.JMenuItem();
        deleteBusTime = new javax.swing.JMenuItem();
        allBusTime = new javax.swing.JMenuItem();
        busFare = new javax.swing.JMenu();
        addBusFare = new javax.swing.JMenuItem();
        editBusFare = new javax.swing.JMenuItem();
        booking = new javax.swing.JMenu();
        addbooking = new javax.swing.JMenuItem();
        bookingDetails = new javax.swing.JMenuItem();
        manageAdmin = new javax.swing.JMenu();
        addAdmin = new javax.swing.JMenuItem();
        editAdmin = new javax.swing.JMenuItem();
        employee = new javax.swing.JMenu();
        addEmployee = new javax.swing.JMenuItem();
        editEmployee = new javax.swing.JMenuItem();
        assignbus = new javax.swing.JMenuItem();
        deleteEmployee = new javax.swing.JMenuItem();
        allEmployee = new javax.swing.JMenuItem();
        report = new javax.swing.JMenu();
        betweenDate = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        manageBus.setText("Manage Bus");

        addBus.setText("Add Bus Details");
        addBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusActionPerformed(evt);
            }
        });
        manageBus.add(addBus);

        editBus.setText("Edit Bus Details");
        editBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBusActionPerformed(evt);
            }
        });
        manageBus.add(editBus);

        deleteBus.setText("Delete Bus Details");
        manageBus.add(deleteBus);

        allBus.setText("All Bus Details");
        allBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBusActionPerformed(evt);
            }
        });
        manageBus.add(allBus);

        jMenuBar1.add(manageBus);

        busTime.setText("Bus Time");

        addBusTime.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addBusTime.setText("Add Bus Time");
        busTime.add(addBusTime);

        editBusTime.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        editBusTime.setText("Edit Bus Time");
        busTime.add(editBusTime);

        deleteBusTime.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteBusTime.setText("Delete Bus Time");
        busTime.add(deleteBusTime);

        allBusTime.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        allBusTime.setText("All Bus Time");
        allBusTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBusTimeActionPerformed(evt);
            }
        });
        busTime.add(allBusTime);

        jMenuBar1.add(busTime);

        busFare.setText("Bus Fare");

        addBusFare.setText("Add Bus Fare");
        busFare.add(addBusFare);

        editBusFare.setText("Edit Bus Fare");
        busFare.add(editBusFare);

        jMenuBar1.add(busFare);

        booking.setText("Booking");

        addbooking.setText("Add Booking");
        addbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookingActionPerformed(evt);
            }
        });
        booking.add(addbooking);

        bookingDetails.setText("Booking Details");
        bookingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingDetailsActionPerformed(evt);
            }
        });
        booking.add(bookingDetails);

        jMenuBar1.add(booking);

        manageAdmin.setText("Manage Admin");

        addAdmin.setText("Add Admin");
        manageAdmin.add(addAdmin);

        editAdmin.setText("Edit Admin");
        manageAdmin.add(editAdmin);

        jMenuBar1.add(manageAdmin);

        employee.setText("Employee");

        addEmployee.setText("Add Employee");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        employee.add(addEmployee);

        editEmployee.setText("Edit Employee");
        editEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeActionPerformed(evt);
            }
        });
        employee.add(editEmployee);

        assignbus.setText("Assign Bus");
        assignbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignbusActionPerformed(evt);
            }
        });
        employee.add(assignbus);

        deleteEmployee.setText("Delete Employee");
        deleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeActionPerformed(evt);
            }
        });
        employee.add(deleteEmployee);

        allEmployee.setText("All Employee");
        allEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allEmployeeActionPerformed(evt);
            }
        });
        employee.add(allEmployee);

        jMenuBar1.add(employee);

        report.setText("Report");

        betweenDate.setText("Between Date");
        report.add(betweenDate);

        jMenuBar1.add(report);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allBusTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBusTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allBusTimeActionPerformed

    private void addBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusActionPerformed
        // TODO add your handling code here:
        AddBusDetail a = new AddBusDetail();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_addBusActionPerformed

    private void allBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBusActionPerformed
        // TODO add your handling code here:
        AllBusDetails a = new AllBusDetails();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_allBusActionPerformed

    private void assignbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignbusActionPerformed
        // TODO add your handling code here:
        AssignBus a = new AssignBus();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_assignbusActionPerformed

    private void addbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookingActionPerformed
        // TODO add your handling code here:
        AddBooking a = new AddBooking();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_addbookingActionPerformed

    private void editBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBusActionPerformed
        // TODO add your handling code here:
        EditBusDetail a = new EditBusDetail();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_editBusActionPerformed

    private void bookingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingDetailsActionPerformed
        // TODO add your handling code here:
        BookingDetails a = new BookingDetails();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_bookingDetailsActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        // TODO add your handling code here:
        AddEmployee a = new AddEmployee();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void allEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allEmployeeActionPerformed
        // TODO add your handling code here:
        AllEmployee a = new AllEmployee();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_allEmployeeActionPerformed

    private void editEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeActionPerformed
        // TODO add your handling code here:
        EditEmployee a = new EditEmployee();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_editEmployeeActionPerformed

    private void deleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeActionPerformed
        // TODO add your handling code here:
        DeleteEmployee a = new DeleteEmployee();
        jDesktopPane1.add(a);
        a.show();
    }//GEN-LAST:event_deleteEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAdmin;
    private javax.swing.JMenuItem addBus;
    private javax.swing.JMenuItem addBusFare;
    private javax.swing.JMenuItem addBusTime;
    private javax.swing.JMenuItem addEmployee;
    private javax.swing.JMenuItem addbooking;
    private javax.swing.JMenuItem allBus;
    private javax.swing.JMenuItem allBusTime;
    private javax.swing.JMenuItem allEmployee;
    private javax.swing.JMenuItem assignbus;
    private javax.swing.JMenuItem betweenDate;
    private javax.swing.JMenu booking;
    private javax.swing.JMenuItem bookingDetails;
    private javax.swing.JMenu busFare;
    private javax.swing.JMenu busTime;
    private javax.swing.JMenuItem deleteBus;
    private javax.swing.JMenuItem deleteBusTime;
    private javax.swing.JMenuItem deleteEmployee;
    private javax.swing.JMenuItem editAdmin;
    private javax.swing.JMenuItem editBus;
    private javax.swing.JMenuItem editBusFare;
    private javax.swing.JMenuItem editBusTime;
    private javax.swing.JMenuItem editEmployee;
    private javax.swing.JMenu employee;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu manageAdmin;
    private javax.swing.JMenu manageBus;
    private javax.swing.JMenu report;
    // End of variables declaration//GEN-END:variables
}
